spring.application.name=pdf-service

llm.url=https://1f747061-c1d2-4fe4-b2a7-55b094834bae.mock.pstmn.io

#Legal Petition Service Client URI
client.legal_petition.host=127.0.0.1:8000
client.legal_petition.context.v1=/legal-petition
